# Generated by Django 5.2.7 on 2025-11-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0002_bet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
