# Generated by Django 5.2.7 on 2025-11-04 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0004_bet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='BulkBetAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SP', 'All SP'), ('DP', 'All DP'), ('JODI', 'Jodi Vagar')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bets', models.IntegerField(default=0)),
                ('jodi_column', models.IntegerField(blank=True, null=True)),
                ('jodi_type', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_undone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='bulk_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bets', to='userbaseapp.bulkbetaction'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'number'], name='userbaseapp_user_id_153865_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', '-created_at'], name='userbaseapp_user_id_d8b7db_idx'),
        ),
    ]
