# Generated by Django 5.2.7 on 2025-11-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0005_alter_bet_options_bulkbetaction_bet_bulk_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('SINGLE', 'Single Bet'), ('SP', 'All SP'), ('DP', 'All DP'), ('JODI', 'Jodi Vagar'), ('DADAR', 'Dadar'), ('EKI', 'Eki'), ('BEKI', 'Beki'), ('ABR_CUT', 'ABR Cut'), ('JODI_PANEL', 'Jodi Panel')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='bet',
            name='column_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='result_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='sub_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='winning_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='action_type',
            field=models.CharField(choices=[('SP', 'All SP'), ('DP', 'All DP'), ('JODI', 'Jodi Vagar'), ('DADAR', 'Dadar'), ('EKI', 'Eki'), ('BEKI', 'Beki'), ('ABR_CUT', 'ABR Cut'), ('JODI_PANEL', 'Jodi Panel')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'bet_type'], name='userbaseapp_user_id_795fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'column_number'], name='userbaseapp_user_id_5bc92f_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['created_at'], name='userbaseapp_created_3dfc14_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['bet_type', 'column_number'], name='userbaseapp_bet_typ_1570ad_idx'),
        ),
    ]
