# Generated by Django 5.2.7 on 2025-11-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0008_alter_bet_bet_type_alter_bulkbetaction_action_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bet', 'verbose_name_plural': 'Bets'},
        ),
        migrations.AlterModelOptions(
            name='bulkbetaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bulk Bet Action', 'verbose_name_plural': 'Bulk Bet Actions'},
        ),
        migrations.AddField(
            model_name='bet',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bet',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bet',
            name='draw_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='draw_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='draw_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='family_group',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='input_digits',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='market_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='payout_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bet',
            name='search_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='bet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='winning_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='columns_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='draw_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='draw_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='family_group',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='family_numbers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='input_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='losing_bets_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='market_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='search_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UNDONE', 'Undone'), ('PARTIAL_UNDONE', 'Partially Undone'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='total_won',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='undone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_bulk_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='winning_bets_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('SINGLE', 'Single Bet'), ('SP', 'All SP'), ('DP', 'All DP'), ('JODI', 'Jodi Vagar'), ('DADAR', 'Dadar'), ('EKI', 'Eki'), ('BEKI', 'Beki'), ('ABR_CUT', 'ABR Cut'), ('JODI_PANEL', 'Jodi Panel'), ('MOTAR', 'Motar'), ('COMMAN_PANA_36', 'Comman Pana 36'), ('COMMAN_PANA_56', 'Comman Pana 56'), ('SET_PANA', 'Set Pana')], db_index=True, default='SINGLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bet',
            name='column_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='is_winner',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='number',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='action_type',
            field=models.CharField(choices=[('SP', 'All SP'), ('DP', 'All DP'), ('JODI', 'Jodi Vagar'), ('DADAR', 'Dadar'), ('EKI', 'Eki'), ('BEKI', 'Beki'), ('ABR_CUT', 'ABR Cut'), ('JODI_PANEL', 'Jodi Panel'), ('MOTAR', 'Motar'), ('COMMAN_PANA_36', 'Comman Pana 36'), ('COMMAN_PANA_56', 'Comman Pana 56'), ('SET_PANA', 'Set Pana')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='is_undone',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='jodi_column',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status'], name='userbaseapp_user_id_27ab33_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'is_winner'], name='userbaseapp_user_id_c11393_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'draw_date'], name='userbaseapp_user_id_4c06f2_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['status', 'is_winner'], name='userbaseapp_status_e57d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['draw_id', 'market_name'], name='userbaseapp_draw_id_8a283c_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['bulk_action', 'created_at'], name='userbaseapp_bulk_ac_3474d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['family_group', 'bet_type'], name='userbaseapp_family__f036ad_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['user', '-created_at'], name='userbaseapp_user_id_77b02b_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['user', 'action_type'], name='userbaseapp_user_id_f19ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['user', 'status'], name='userbaseapp_user_id_aa0a13_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['action_type', 'created_at'], name='userbaseapp_action__d79941_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['is_undone', 'status'], name='userbaseapp_is_undo_af175f_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['draw_id', 'market_name'], name='userbaseapp_draw_id_8c165a_idx'),
        ),
    ]
