# Generated by Django 5.2.7 on 2025-11-15 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0010_remove_bet_userbaseapp_user_id_c11393_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='action_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bulkbetaction',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'bazar', 'bet_date'], name='userbaseapp_user_id_d02a25_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['bazar', 'bet_date'], name='userbaseapp_bazar_b00a72_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['user', 'bazar', 'action_date'], name='userbaseapp_user_id_aa9828_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkbetaction',
            index=models.Index(fields=['bazar', 'action_date'], name='userbaseapp_bazar_c6c8f5_idx'),
        ),
    ]
