# Generated by Django 5.2.7 on 2025-11-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0011_bet_bazar_bet_bet_date_bulkbetaction_action_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed'), ('MAIN_BAZAR', 'Main Bazar'), ('MAIN_BAZAR_CLOSED', 'Main Bazar Closed')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed'), ('MAIN_BAZAR', 'Main Bazar'), ('MAIN_BAZAR_CLOSED', 'Main Bazar Closed')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
    ]
