# Generated by Django 5.2.7 on 2025-11-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0013_alter_bet_bet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('SINGLE', 'Single Bet'), ('SP', 'All SP'), ('DP', 'All DP'), ('JODI', 'Jodi Vagar'), ('DADAR', 'Dadar'), ('EKI', 'Eki'), ('BEKI', 'Beki'), ('ABR_CUT', 'ABR Cut'), ('JODI_PANEL', 'Jodi Panel'), ('MOTAR', 'Motar'), ('COMMAN_PANA_36', 'Comman Pana 36'), ('COMMAN_PANA_56', 'Comman Pana 56'), ('SET_PANA', 'Set Pana'), ('COLUMN', 'Column Bet'), ('GROUP', 'Group Bet')], db_index=True, default='SINGLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='action_type',
            field=models.CharField(choices=[('SP', 'All SP'), ('DP', 'All DP'), ('JODI', 'Jodi Vagar'), ('DADAR', 'Dadar'), ('EKI', 'Eki'), ('BEKI', 'Beki'), ('ABR_CUT', 'ABR Cut'), ('JODI_PANEL', 'Jodi Panel'), ('MOTAR', 'Motar'), ('COMMAN_PANA_36', 'Comman Pana 36'), ('COMMAN_PANA_56', 'Comman Pana 56'), ('SET_PANA', 'Set Pana'), ('GROUP', 'Group Bet')], db_index=True, max_length=20),
        ),
    ]
