# Generated by Django 5.2.7 on 2025-12-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0014_alter_bet_bet_type_alter_bulkbetaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed'), ('MAIN_BAZAR', 'Main Bazar'), ('MAIN_BAZAR_CLOSED', 'Main Bazar Closed'), ('CM_9', 'CM-9'), ('CM_10', 'CM-10'), ('CM_11', 'CM-11'), ('CM_12', 'CM-12')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed'), ('MAIN_BAZAR', 'Main Bazar'), ('MAIN_BAZAR_CLOSED', 'Main Bazar Closed'), ('CM_9', 'CM-9'), ('CM_10', 'CM-10'), ('CM_11', 'CM-11'), ('CM_12', 'CM-12')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
    ]
