# Generated by Django 5.2.7 on 2025-12-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbaseapp', '0015_add_cm_bazars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed'), ('MAIN_BAZAR', 'Main Bazar'), ('MAIN_BAZAR_CLOSED', 'Main Bazar Closed'), ('CM_1', 'CM-1'), ('CM_2', 'CM-2'), ('CM_3', 'CM-3'), ('CM_4', 'CM-4'), ('CM_5', 'CM-5'), ('CM_6', 'CM-6'), ('CM_7', 'CM-7'), ('CM_8', 'CM-8'), ('CM_9', 'CM-9'), ('CM_10', 'CM-10'), ('CM_11', 'CM-11'), ('CM_12', 'CM-12')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='bulkbetaction',
            name='bazar',
            field=models.CharField(choices=[('SRIDEVI_OPEN', 'Sridevi Open'), ('SRIDEVI_CLOSED', 'Sridevi Closed'), ('TIME_OPEN', 'Time Open'), ('TIME_CLOSED', 'Time Closed'), ('DIVAS_MILAN_OPEN', 'Divas Milan Open'), ('DIVAS_MILAN_CLOSED', 'Divas Milan Closed'), ('KALYAN_OPEN', 'Kalyan Open'), ('KALYAN_CLOSED', 'Kalyan Closed'), ('NIGHT_MILAN_OPEN', 'Night Milan Open'), ('NIGHT_MILAN_CLOSED', 'Night Milan Closed'), ('MAIN_BAZAR', 'Main Bazar'), ('MAIN_BAZAR_CLOSED', 'Main Bazar Closed'), ('CM_1', 'CM-1'), ('CM_2', 'CM-2'), ('CM_3', 'CM-3'), ('CM_4', 'CM-4'), ('CM_5', 'CM-5'), ('CM_6', 'CM-6'), ('CM_7', 'CM-7'), ('CM_8', 'CM-8'), ('CM_9', 'CM-9'), ('CM_10', 'CM-10'), ('CM_11', 'CM-11'), ('CM_12', 'CM-12')], db_index=True, default='SRIDEVI_OPEN', max_length=30),
        ),
    ]
